interface InterfaceList {
  apelido: string,
  cod_empresa: number,
  codcoligada: number,
  codfilial: number,
  colaborador: string,
  codigo_cpf: string,
  dataadmissao: Date,
  cod_funcao: string,
  funcao: string,
  banco: string,
  agencia: string,
  digito_agencia: string,
  conta: string,
  digito_conta: string,
  valor_decimo: number,
  ano_ref: number,
  cod_band: number,
  grupo_funcao: number,
  grupo: number,
  nota_gerencia: number,
  nota_comercial: number,
  nota_adm: number,
  categoria_pplr: 2,
  categoria: string,
  pf_final: number,
  categoria_calculo: string,
  notacalculo: number,
  basenota: number,
  valor_possivel: number,
  valor_lucro: number,
  codccusto: number,
  conta_tipo: number,
  valor_limite_distribuicao_original: number,
  somatotal: number,
  valor_limite_ajustado: number,
  descontos_empresa: number|null,
  valor_limite_pagar: number,
  percentual_representa: number,
  valor_final: number
}

export type {
  InterfaceList
};

