interface InterfaceList {
  apelido: string,
  cod_empresa: number,
  codigo_cpf: number,
  ano_ref: number,
  parametro: string,
  cod_band: number,
  colaborador: string,
  funcao: string,
  cod_funcao: number,
  empresa: string,
  grupo_funcao: number,
  grupo: number,
  cod_depto: number,
  meta_jan: number,
  realizado_jan: number,
  desvio_jan: number,
  nota_jan: number,
  meta_fev: number,
  realizado_fev: number,
  desvio_fev: number,
  nota_fev: number,
  meta_mar: number,
  realizado_mar: number,
  desvio_mar: number,
  nota_mar: number,
  meta_abr: number,
  realizado_abr: number,
  desvio_abr: number,
  nota_abr: number,
  meta_mai: number,
  realizado_mai: number,
  desvio_mai: number,
  nota_mai: number,
  meta_jun: number,
  realizado_jun: number,
  desvio_jun: number,
  nota_jun: number,
  meta_jul: number,
  realizado_jul: number,
  desvio_jul: number,
  nota_jul: number,
  meta_ago: number,
  realizado_ago: number,
  desvio_ago: number,
  nota_ago: number,
  meta_set: number,
  realizado_set: number,
  desvio_set: number,
  nota_set: number,
  meta_out: number,
  realizado_out: number,
  desvio_out: number,
  nota_out: number,
  meta_nov: number,
  realizado_nov: number,
  desvio_nov: number,
  nota_nov: number,
  meta_dez: number,
  realizado_dez: number,
  desvio_dez: number,
  nota_dez: number,
  meta_ac: number,
  realizado_ac: number,
  desvio_ac: number,
  departamento: string,
}

export type {
  InterfaceList
};

