/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlertDefault: typeof import('./components/alerts/AlertDefault.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppLauncher: typeof import('./components/apps/AppLauncher.vue')['default']
    BaseDataTable: typeof import('./components/tables/BaseDataTable.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    KpiCard: typeof import('./components/KpiCard.vue')['default']
    MenuFilterSelect: typeof import('./components/tables/filters/MenuFilterSelect.vue')['default']
    NotificationBox: typeof import('./components/Notifications/NotificationBox.vue')['default']
    PageBreadcrumb: typeof import('./components/PageBreadcrumb.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableFilterGroup: typeof import('./components/tables/filters/TableFilterGroup.vue')['default']
  }
}
