/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/colaboradores/': RouteRecordInfo<
      '/colaboradores/',
      '/colaboradores',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/exportacao/': RouteRecordInfo<
      '/exportacao/',
      '/exportacao',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/importacao/': RouteRecordInfo<
      '/importacao/',
      '/importacao',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/importacao/cnpj': RouteRecordInfo<
      '/importacao/cnpj',
      '/importacao/cnpj',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/importacao/contrato': RouteRecordInfo<
      '/importacao/contrato',
      '/importacao/contrato',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/PageNotFound': RouteRecordInfo<
      '/PageNotFound',
      '/PageNotFound',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/processos/': RouteRecordInfo<
      '/processos/',
      '/processos',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/processos/historico': RouteRecordInfo<
      '/processos/historico',
      '/processos/historico',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/': RouteRecordInfo<
      '/relatorios/',
      '/relatorios',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/centro-custo': RouteRecordInfo<
      '/relatorios/centro-custo',
      '/relatorios/centro-custo',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/colaborador': RouteRecordInfo<
      '/relatorios/colaborador',
      '/relatorios/colaborador',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/empresa': RouteRecordInfo<
      '/relatorios/empresa',
      '/relatorios/empresa',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/nao-pagamento': RouteRecordInfo<
      '/relatorios/nao-pagamento',
      '/relatorios/nao-pagamento',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/pagamento': RouteRecordInfo<
      '/relatorios/pagamento',
      '/relatorios/pagamento',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/resumo-depto': RouteRecordInfo<
      '/relatorios/resumo-depto',
      '/relatorios/resumo-depto',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/colaboradores/index.vue': {
      routes:
        | '/colaboradores/'
      views:
        | never
    }
    'src/pages/exportacao/index.vue': {
      routes:
        | '/exportacao/'
      views:
        | never
    }
    'src/pages/importacao/index.vue': {
      routes:
        | '/importacao/'
      views:
        | never
    }
    'src/pages/importacao/cnpj.vue': {
      routes:
        | '/importacao/cnpj'
      views:
        | never
    }
    'src/pages/importacao/contrato.vue': {
      routes:
        | '/importacao/contrato'
      views:
        | never
    }
    'src/pages/PageNotFound.vue': {
      routes:
        | '/PageNotFound'
      views:
        | never
    }
    'src/pages/processos/index.vue': {
      routes:
        | '/processos/'
      views:
        | never
    }
    'src/pages/processos/historico.vue': {
      routes:
        | '/processos/historico'
      views:
        | never
    }
    'src/pages/relatorios/index.vue': {
      routes:
        | '/relatorios/'
      views:
        | never
    }
    'src/pages/relatorios/centro-custo.vue': {
      routes:
        | '/relatorios/centro-custo'
      views:
        | never
    }
    'src/pages/relatorios/colaborador.vue': {
      routes:
        | '/relatorios/colaborador'
      views:
        | never
    }
    'src/pages/relatorios/empresa.vue': {
      routes:
        | '/relatorios/empresa'
      views:
        | never
    }
    'src/pages/relatorios/nao-pagamento.vue': {
      routes:
        | '/relatorios/nao-pagamento'
      views:
        | never
    }
    'src/pages/relatorios/pagamento.vue': {
      routes:
        | '/relatorios/pagamento'
      views:
        | never
    }
    'src/pages/relatorios/resumo-depto.vue': {
      routes:
        | '/relatorios/resumo-depto'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
