/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/dashboard/': RouteRecordInfo<
      '/dashboard/',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/PageNotFound': RouteRecordInfo<
      '/PageNotFound',
      '/PageNotFound',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/dados/': RouteRecordInfo<
      '/relatorios/dados/',
      '/relatorios/dados',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/final/': RouteRecordInfo<
      '/relatorios/final/',
      '/relatorios/final',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/notas/': RouteRecordInfo<
      '/relatorios/notas/',
      '/relatorios/notas',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/relatorios/valores-possiveis/': RouteRecordInfo<
      '/relatorios/valores-possiveis/',
      '/relatorios/valores-possiveis',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/dashboard/index.vue': {
      routes:
        | '/dashboard/'
      views:
        | never
    }
    'src/pages/PageNotFound.vue': {
      routes:
        | '/PageNotFound'
      views:
        | never
    }
    'src/pages/relatorios/dados/index.vue': {
      routes:
        | '/relatorios/dados/'
      views:
        | never
    }
    'src/pages/relatorios/final/index.vue': {
      routes:
        | '/relatorios/final/'
      views:
        | never
    }
    'src/pages/relatorios/notas/index.vue': {
      routes:
        | '/relatorios/notas/'
      views:
        | never
    }
    'src/pages/relatorios/valores-possiveis/index.vue': {
      routes:
        | '/relatorios/valores-possiveis/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
